server:
  port: ${ORDER_SYSTEM_PORT}

spring:
  application:
    name: order-system

  datasource:
    url: ${ORDER_SYSTEM_POSTGRES_URL}
    username: ${ORDER_SYSTEM_POSTGRES_USERNAME}
    password: ${ORDER_SYSTEM_POSTGRES_PASSWORD}

