server:
  port: ${ORDER_API_ENGINE_PORT:8081}

spring:
  application:
    name: order-api-engine

  datasource:
    url: ${ORDER_API_ENGINE_POSTGRES_URL}
    username: ${ORDER_API_ENGINE_POSTGRES_USERNAME}
    password: ${ORDER_API_ENGINE_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${ORDER_API_ENGINE_KAFKA_HOST}:${ORDER_API_ENGINE_KAFKA_PORT}

    consumer:
      group-id: order-api-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer